// Code generated by "stringer -type Kind kind.go"; DO NOT EDIT.

package spec

import "strconv"

const _Kind_name = "InvalidBoolIntInt8Int16Int32Int64UintUint8Uint16Uint32Uint64UintptrFloat32Float64Complex64Complex128StringByteRuneErrorArrayChanFuncInterfaceMapPtrSliceStructTimeDuration"

var _Kind_index = [...]uint8{0, 7, 11, 14, 18, 23, 28, 33, 37, 42, 48, 54, 60, 67, 74, 81, 90, 100, 106, 110, 114, 119, 124, 128, 132, 141, 144, 147, 152, 158, 162, 170}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
