package run

import (
	"bytes"
	"encoding/json"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/wzshiming/gen/openapi"
	"github.com/wzshiming/gen/parser"
	"github.com/wzshiming/gen/route"
	"github.com/wzshiming/gotype"
	oaspec "github.com/wzshiming/openapi/spec"
)

func Run(pkgs []string, port string, way string) error {
	f, err := file(pkgs, port, way)
	if err != nil {
		return err
	}
	path := filepath.Join(os.TempDir(), "main.go")
	err = ioutil.WriteFile(path, f, 0666)
	if err != nil {
		return err
	}

	cmd := exec.Command("go", "run", path)
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout
	err = cmd.Run()
	if err != nil {
		return err
	}
	return nil
}

func file(pkgs []string, port string, way string) ([]byte, error) {
	imp := gotype.NewImporter(gotype.WithCommentLocator())
	def := parser.NewParser(imp)

	for _, pkg := range pkgs {
		err := def.Import(pkg, way)
		if err != nil {
			return nil, err
		}
	}

	server := "http://127.0.0.1" + port

	router, err := route.NewGenRoute(def.API()).Generate("main", ".", "Router")
	if err != nil {
		return nil, err
	}
	router.AddImport("", "net/http")
	router.AddImport("", "fmt")
	router.AddImport("", "github.com/urfave/negroni")
	router.AddImport("", "github.com/wzshiming/gen/ui/swaggerui")
	router.AddImport("", "github.com/wzshiming/gen/ui/redoc")

	api, err := openapi.NewGenOpenAPI(def.API()).SetInfo(&oaspec.Info{
		Title:       "OpenAPI Demo",
		Description: "The current environment is only used for testing documents, and some interfaces do not work properly. Generated by gen run " + strings.Join(pkgs, " "),
		Version:     "test",
		Contact: &oaspec.Contact{
			Name: "wzshiming",
			URL:  "https://github.com/wzshiming/gen",
		},
	}).WithServices(server).Generate()
	if err != nil {
		return nil, err
	}

	d, err := json.MarshalIndent(api, "", " ")
	if err != nil {
		return nil, err
	}

	buf := bytes.NewBuffer(nil)
	err = tpl.Execute(buf, map[string]interface{}{
		"Openapi": "`" + string(d) + "`",
		"Server":  server,
		"Port":    port,
		"Router":  router,
	})
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

var tpl = template.Must(template.New("").Parse(temp))

const temp = `//+build ignore

{{ .Router }}

var openapi = []byte({{ .Openapi }})

func main() {
	mux := &http.ServeMux{}
	mux.Handle("/", Router())

	mux.Handle("/swagger/", http.StripPrefix("/swagger", swaggerui.HandleWithFile("openapi.json", openapi)))
	mux.Handle("/redoc/", http.StripPrefix("/redoc", redoc.HandleWithFile("openapi.json", openapi)))
	fmt.Printf("Open {{ .Server }}/swagger/# or {{ .Server }}/redoc/# with your browser.\n")

	n := negroni.New(negroni.NewRecovery(), negroni.NewLogger())
	n.UseHandler(mux)
	err := http.ListenAndServe("{{ .Port }}", n)
	if err != nil {
		fmt.Println(err)
	}
	return
}

`
